name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Change to the branch you use for development if it's not `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'  # Make sure it matches your Blazor app's SDK version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Publish Blazor WebAssembly app to a folder
      - name: Build and Publish Blazor WebAssembly
        run: dotnet publish -c Release -o ./publish

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
          publish_dir: ./publish/wwwroot  # The folder containing the built Blazor app
